let deferredInstallPrompt=null;const installButton=document.getElementById('installButton'),modalInstall=document.getElementById('modalInstall'),installModal=document.getElementById('installModal'),openInstallGuide=document.getElementById('openInstallGuide'),closeInstall=document.getElementById('closeInstall'),manualGuide=document.getElementById('manualGuide'),manualText=document.getElementById('manualText'),installedNote=document.getElementById('installedNote'),toast=document.getElementById('toast'),syncStatus=document.getElementById('syncStatus');
const isStandalone=()=>window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),3000)}
function setStatus(){const online=navigator.onLine;syncStatus.innerHTML=`<i style="color:${online?'#73e6ae':'#ffbf69'}"></i><span>${online?'ONLINE':'OFFLINE — LOCAL MODE'}</span>`}
function openModal(){installModal.hidden=false;document.body.style.overflow='hidden';if(deferredInstallPrompt)modalInstall.hidden=false;}
function closeModal(){installModal.hidden=true;document.body.style.overflow=''}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;installButton.hidden=false;modalInstall.hidden=false});
async function install(){if(!deferredInstallPrompt){showToast('Use your browser menu to install MERCYVERSE on this device.');return}deferredInstallPrompt.prompt();const result=await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;installButton.hidden=true;modalInstall.hidden=true;showToast(result.outcome==='accepted'?'MERCYVERSE is being installed ✦':'Installation was cancelled.');}
installButton.addEventListener('click',install);modalInstall.addEventListener('click',install);openInstallGuide.addEventListener('click',openModal);closeInstall.addEventListener('click',closeModal);installModal.addEventListener('click',e=>{if(e.target===installModal)closeModal()});
manualGuide.addEventListener('click',()=>{manualText.hidden=!manualText.hidden;manualText.innerHTML=/<iPhone|iPad|Macintosh/.test(navigator.userAgent)?'<b>Apple devices:</b> open this page in Safari, use the Share button, then choose <b>Add to Home Screen</b>.':'<b>Android/Chrome:</b> tap the browser menu and choose <b>Install app</b> or <b>Add to Home screen</b>. <br><br><b>Windows/Edge/Chrome:</b> use the install icon in the address bar or browser menu. <br><br><b>After installation:</b> launch MERCYVERSE from its new app icon — the manifest requests standalone mode, so the normal address bar is not part of the app window.'});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;installButton.hidden=true;modalInstall.hidden=true;installedNote.hidden=false;showToast('Welcome to the installed MERCYVERSE app ✦')});
window.addEventListener('online',setStatus);window.addEventListener('offline',setStatus);setStatus();if(isStandalone()){installedNote.hidden=false;installButton.hidden=true}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').then(()=>console.log('MERCYVERSE service worker ready')).catch(err=>console.error('SW registration failed',err)))}
